### ISSUE TITLE
Windows 10 Installation 

### ISSUE THREAD

**Issue by cwild-UoS** [CITCOM-project/CausalTestingFramework#41]
When installing the dependencies of the project on my windows 10 YoYo laptop the 'econml' package fails to install correctly.

Steps taken:
Inside a clone of the latest main branch:

```
conda create -y --force -n ctf
conda activate ctf
conda install -c conda-forge pygraphviz
pip install -e .

```

Traceback:

```
(ctf) C:\Users\cs1xcw\Documents\CausalTestingFramework>pip install -e .
Obtaining file:///C:/Users/cs1xcw/Documents/CausalTestingFramework
  Preparing metadata (setup.py) ... done
Collecting numpy~=1.20
  Downloading numpy-1.22.2-cp310-cp310-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 8.0 MB/s eta 0:00:00
Collecting pandas~=1.3.4
  Using cached pandas-1.3.5-cp310-cp310-win_amd64.whl (10.2 MB)
Collecting setuptools~=58.5.3
  Using cached setuptools-58.5.3-py3-none-any.whl (946 kB)
Collecting networkx~=2.6.3
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Requirement already satisfied: pygraphviz~=1.7 in c:\users\cs1xcw\miniconda3\envs\ctf\lib\site-packages (from causal-testing-framework==0.0.1) (1.9)
Collecting pytest~=6.2.5
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting scikit-learn~=1.0.1
  Using cached scikit_learn-1.0.2-cp310-cp310-win_amd64.whl (7.2 MB)
Collecting matplotlib~=3.5.0
  Using cached matplotlib-3.5.1-cp310-cp310-win_amd64.whl (7.2 MB)
Collecting econml~=0.12.0
  Using cached econml-0.12.0.tar.gz (1.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting statsmodels~=0.13.1
  Downloading statsmodels-0.13.2-cp310-cp310-win_amd64.whl (9.1 MB)
     ---------------------------------------- 9.1/9.1 MB 8.2 MB/s eta 0:00:00
Collecting z3-solver~=4.8.13.0
  Using cached z3_solver-4.8.13.0-py2.py3-none-win_amd64.whl (35.5 MB)
Collecting lhsmdu
  Using cached lhsmdu-1.1-py2.py3-none-any.whl (5.6 kB)
Collecting tabulate
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting scipy~=1.7.2
  Using cached scipy-1.7.3-cp310-cp310-win_amd64.whl (34.3 MB)
Collecting sparse
  Using cached sparse-0.13.0-py2.py3-none-any.whl (77 kB)
Collecting dowhy
  Using cached dowhy-0.7-py3-none-any.whl (152 kB)
Collecting lightgbm
  Using cached lightgbm-3.3.2-py3-none-win_amd64.whl (1.0 MB)
Collecting joblib>=0.13.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Collecting shap<0.40.0,>=0.38.1
  Using cached shap-0.39.0.tar.gz (356 kB)
  Preparing metadata (setup.py) ... done
Collecting numba!=0.42.1
  Downloading numba-0.55.1-cp310-cp310-win_amd64.whl (2.4 MB)
     ---------------------------------------- 2.4/2.4 MB 7.9 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.2-cp310-cp310-win_amd64.whl (52 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.0.1-cp310-cp310-win_amd64.whl (3.2 MB)
     ---------------------------------------- 3.2/3.2 MB 7.9 MB/s eta 0:00:00
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.29.1-py3-none-any.whl (895 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting attrs>=19.2.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting patsy>=0.5.2
  Using cached patsy-0.5.2-py2.py3-none-any.whl (233 kB)
Collecting numpy~=1.20
  Using cached numpy-1.21.5-cp310-cp310-win_amd64.whl (14.0 MB)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.0-cp310-cp310-win_amd64.whl (23.2 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting tqdm>4.25.0
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting slicer==0.0.7
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting cloudpickle
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Collecting pydot>=1.4
  Using cached pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Collecting sympy>=1.4
  Using cached sympy-1.9-py3-none-any.whl (6.2 MB)
Requirement already satisfied: wheel in c:\users\cs1xcw\miniconda3\envs\ctf\lib\site-packages (from lightgbm->econml~=0.12.0->causal-testing-framework==0.0.1) (0.37.1)
Collecting mpmath>=0.19
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
Building wheels for collected packages: econml, shap
  Building wheel for econml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for econml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'econml\solutions\__init__.py' not found (or not a regular file)
      package init file 'econml\data\ihdp\__init__.py' not found (or not a regular file)
      package init file 'econml\data\input_dynamicdgp\__init__.py' not found (or not a regular file)
      running build_ext
      building 'econml.grf._criterion' extension
      Traceback (most recent call last):
        File "C:\Users\cs1xcw\Miniconda3\envs\ctf\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\cs1xcw\Miniconda3\envs\ctf\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\cs1xcw\Miniconda3\envs\ctf\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 35, in <module>
          setup(ext_modules=c_extensions + pyx_extensions,
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
          _build_ext.build_ext.build_extensions(self)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
          self.initialize()
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\cs1xcw\AppData\Local\Temp\pip-build-env-_5ai_q30\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for econml
  Building wheel for shap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      The nvcc binary could not be located in your $PATH. Either  add it to your path, or set $CUDAHOME to enable CUDA
      Error building cuda module: TypeError('cannot unpack non-iterable NoneType object')
      WARNING: Could not compile cuda extensions
      C:\Users\cs1xcw\Miniconda3\envs\ctf\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      running build_ext
      numpy.get_include() c:\users\cs1xcw\appdata\local\temp\pip-install-w156l_nb\shap_6451fc48d5f84c8e887a0a5e376f0726\.eggs\numpy-1.22.2-py3.10-win-amd64.egg\numpy\core\include
      building 'shap._cext' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shap
  Running setup.py clean for shap
Failed to build econml shap
ERROR: Could not build wheels for econml, which is required to install pyproject.toml-based projects
```

**Comment by cwild-UoS** [comment]
As @bobturneruk points out, in ci-tests.yaml, windows-latest is tested. However 'Microsoft Visual C++ 14.0 or greater' may come with githubs standard windows runner

https://github.com/CITCOM-project/CausalTestingFramework/blob/b12a3bfff13e6de04860db8c724abbe78737fef6/.github/workflows/ci-tests.yaml#L14

**Comment by cwild-UoS** [comment]
Downloading the latest 'Microsoft Visual C++' (https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), has allowed me to install the dependencies on windows 10 without issue. 

Is it worth listing Visual C++ in the installation instructions as a dependency for windows, when they are made?

**Comment by bobturneruk** [comment]
Yes (please?).

**Comment by cwild-UoS** [comment]
Included in the sphinx docs installation page now
