### ISSUE TITLE
Estimation of non-numeric values

### ISSUE THREAD

**Issue by jmafoster1** [CITCOM-project/CausalTestingFramework#46]
When the treatment (and presumably the outcome) is non-numeric, the LinearRegression estimator crashes out with a long stack trace
```
Traceback (most recent call last):
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/compare_interventions_basic.py", line 53, in step_impl
          causal_test_result = causal_test_engine.execute_test(estimation_model)
        File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/testing/causal_test_engine.py", line 127, in execute_test
          ate, confidence_intervals = estimator.estimate_ate()
        File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/testing/estimators.py", line 127, in estimate_ate
          model = self._run_linear_regression()
        File "/home/michael/Documents/CITCoM/CausalTestingFramework/causal_testing/testing/estimators.py", line 158, in _run_linear_regression
          regression = sm.OLS(outcome_col, treatment_and_adjustments_cols)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 892, in __init__
          super(OLS, self).__init__(endog, exog, missing=missing,
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 719, in __init__
          super(WLS, self).__init__(endog, exog, missing=missing,
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/regression/linear_model.py", line 193, in __init__
          super(RegressionModel, self).__init__(endog, exog, **kwargs)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/model.py", line 267, in __init__
          super().__init__(endog, exog, **kwargs)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/model.py", line 92, in __init__
          self.data = self._handle_data(endog, exog, missing, hasconst,
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/model.py", line 132, in _handle_data
          data = handle_data(endog, exog, missing, hasconst, **kwargs)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/data.py", line 673, in handle_data
          return klass(endog, exog=exog, missing=missing, hasconst=hasconst,
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/data.py", line 82, in __init__
          self.endog, self.exog = self._convert_endog_exog(endog, exog)
        File "/home/michael/anaconda3/envs/causecumber/lib/python3.9/site-packages/statsmodels/base/data.py", line 507, in _convert_endog_exog
          raise ValueError("Pandas data cast to numpy dtype of object. "
      ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
```
I think the data needs to be preprocessed to assign numerical values to non-numeric ones, or alternatively we should perform some sort of validation and advise the use of a different estimator. Thoughts?

**Comment by jmafoster1** [comment]
We now have the `LogisticRegressionEstimator` class to estimate binary outcomes. Categorical outcomes still require a custom estimator.
